neo_simulation2 Humble branch updated with arm support and urdf files updated to modular xacros
neobotix/neo_simulation2 pull request #101
Opened 2024-10-22 09:22 UTC by AdarshKaran

arm type validation for mpo_500 and mpo_700, ROS2 control node integration for UR arms and modularization of robot description files into xacro format to reduce redundancy. Additionally, the package structure has been reorganized to support Xacro files, and the caster model for MPO-700 has been updated (see issue #99).

2024-10-28 16:54 UTC, padhupradheep commented
https://github.com/user-attachments/assets/470d651c-3f92-4663-aba3-fca847d14be6

here is a sample video

2024-11-22 13:15 UTC, padhupradheep requested changes
Overall LGTM. Just some minor changes before this goes in.

2024-11-22 13:15 UTC, padhupradheep commented on configs/ur_config/ur10/moveit_controllers.yaml
Please remove this file, it is not required here.

2024-11-22 13:15 UTC, padhupradheep commented on configs/ur_config/ompl_planning.yaml
This file is also not required, please remove it as well.

2024-11-22 13:15 UTC, padhupradheep commented on README.md
> +# Neobotix Neo Simulation2 Package - Contribution Overview
Could you please check our updated documentation website and tell me what exact changes that needs to be made ? 

We don't want an additional readme.

2024-11-22 16:54 UTC, AdarshKaran commented on configs/ur_config/ur10/moveit_controllers.yaml
i have removed both the moveit files Pradheep.

2024-11-25 10:00 UTC, padhupradheep commented
I have tested the changes @AdarshKaran, works really good. This is how I wanted it to be exact. One minor point, if a user uses the `arm_type` argument with an MP-500 or MP-400. I want to leave it as such, we can fix that later when someone complains.

2024-11-25 10:00 UTC, merged